package com.guardaestados.ui.theme

import androidx.compose.ui.graphics.Color

val SocialNightBackground = Color(0xFF061413)
val SocialNightSurface = Color(0xCC111B19)
val SocialNightSurfaceHigh = Color(0xD91A2421)
val SocialNightSurfaceHighest = Color(0xE6232E2A)
val SocialTextPrimary = Color(0xFFF7FAF8)
val SocialTextSecondary = Color(0xFFC5D0CB)
val SocialBorder = Color(0x4DFFFFFF)
val SocialGreen = Color(0xFF25D979)
val SocialGreenSoft = Color(0x3325D979)
val SocialViolet = Color(0xFF4CBF92)
val SocialFuchsia = Color(0xFF63D5A4)

val NeutralLightBackground = Color(0xFFF8FAFC)
val NeutralLightSurface = Color(0xFFFFFFFF)
val NeutralLightSurfaceHigh = Color(0xFFEFF3F7)
val NeutralLightSurfaceHighest = Color(0xFFE1E7EF)
val NeutralLightTextPrimary = Color(0xFF111827)
val NeutralLightTextSecondary = Color(0xFF52606F)
val NeutralLightBorder = Color(0xFFC5CED8)
val NeutralLightPrimary = Color(0xFF36515F)
val NeutralLightOnPrimary = Color(0xFFFFFFFF)
val NeutralLightSecondary = Color(0xFF5D6470)

val NeutralDarkBackground = Color(0xFF071716)
val NeutralDarkSurface = Color(0xE6121C1A)
val NeutralDarkSurfaceHigh = Color(0xE61B2623)
val NeutralDarkSurfaceHighest = Color(0xF024302C)
val NeutralDarkTextPrimary = Color(0xFFF3F7F5)
val NeutralDarkTextSecondary = Color(0xFFC1CCC8)
val NeutralDarkBorder = Color(0x59FFFFFF)
val NeutralDarkPrimary = SocialGreen
val NeutralDarkOnPrimary = Color(0xFF03100B)
val NeutralDarkSecondary = Color(0xFFD0D8D5)

val SocialError = Color(0xFFFFB4AB)
val SocialOnError = Color(0xFF690005)
val SocialErrorContainer = Color(0xFF93000A)
val SocialOnErrorContainer = Color(0xFFFFDAD6)
val NeutralLightError = Color(0xFFBA1A1A)
val NeutralLightOnError = Color(0xFFFFFFFF)
val NeutralLightErrorContainer = Color(0xFFFFDAD6)
val NeutralLightOnErrorContainer = Color(0xFF410002)
val NeutralDarkError = Color(0xFFFFB4AB)
val NeutralDarkOnError = Color(0xFF690005)
val NeutralDarkErrorContainer = Color(0xFF93000A)
val NeutralDarkOnErrorContainer = Color(0xFFFFDAD6)